version: "3.3"
services:
  caddy:
    image: docker.io/lucaslorentz/caddy-docker-proxy:2.7-alpine
    environment:
      TZ: Europe/Zurich
      # TLS
      EMAIL: ${CADDY_TLS_EMAIL}
      # CADDY
      CADDY_INGRESS_NETWORKS: caddy
      CADDY_DOCKER_CADDYFILE_PATH: "/work/Caddyfile"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./local-certs:/data/caddy/pki/authorities/local
      - ./Caddyfile:/work/Caddyfile
      - caddy-data:/data
    ports:
      # WEB
      - "80:80"
      - "443:443"
    networks:
      - public
      - caddy
    labels:
      caddy: ${CADDY_BASE_URL}
      caddy.respond: "404"
      # health endpoint
      caddy.handle_path: "/health"
      caddy.handle_path.respond: '"<p>&#128075;</p>" 200'
      caddy.handle_path.respond.close:
    hostname: caddy
    container_name: caddy
    restart: always

volumes:
  caddy-data: {}

networks:
  public:
    internal: false
  caddy:
    external: true

